<?php
use Doctrine\ORM\Query\AST\Functions\SubstringFunction;
?>
<div id="tituloPagina">Cadastro de Instrutores<br/><br/>Instrutores cadastrados</div>


<table class="hover" id="consulta">
<thead>
<tr>
<th style="text-align: left;">Nome</th>
<th style="text-align: left;">Email</th>
<th style="text-align: left;">Telefone celular</th>
<th style="text-align: left;">Currículo</th>
<th style="text-align: left;">Instituição</th>
<th width="90" class="center">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($instrutores as $instrutor):?>
		<tr>
			<td id="nome"><?php echo $this->escapeHtml($instrutor->getNome());?></td>
			<td><?php echo $this->escapeHtml($instrutor->getEmail());?></td>
			<td><?php echo $this->escapeHtml($instrutor->getCelular());?></td>
			<td><?php echo $this->escapeHtml(substr($instrutor->getCurriculo(),0,60).
					"...");?></td>
			<td><?php echo $this->escapeHtml($instrutor->getInstituicao()->getRazao());?></td>
			<td style="text-align:center">
				<a href="/application/instrutor/save/id/<?php echo $instrutor->getId();?>"><span title="Editar" class="ui-icon ui-icon-pencil"/></a>
				<a href="/application/instrutor/delete/id/<?php echo $instrutor->getId();?>" id="excluir"><span title="Excluir" class="ui-icon ui-icon-trash"/></a>
			</td> 
		</tr>
	<?php endforeach;?>
</table>
<div id="barraBotoes">
	<button id="novo">Novo...</button>
</div>
<div id="dialog-form" title="Confirmar exclusão">
	<p id="texto"/>
</div>

<script>
	$("#novo").button({
		icons: {
			primary: "ui-icon-plus",
		},
	text: true,
	});
	$("#novo").click(function(e) {
		e.preventDefault();
		window.location ="/application/instrutor/save";
	});
	
    $("input[type=submit], a" ).button();

    $("a#excluir").on("click", function(e) {
        e.preventDefault();
        var link = $(this).attr('href');
        var nome = $(this).closest('tr').find('#nome').text();
        $("#texto").html("Deseja realmente excluir '"+nome+"'?");
        $("#dialog-form").data("link", link);
        $("#dialog-form").dialog("open");
    });

     $( "#dialog-form" ).dialog({
		dialogClass: 'no-close',
        autoOpen: false,
        resizable: false,
        draggable: false,
        height: 200,
        width: 300,
        modal: true,
        buttons: {
        		"Sim": function() {
        		var link = $(this).data("link");
            	window.location = link;
         	  },
     			"Não": function() {
         		$(this).dialog("close");
         	}
	}
    });
   
</script>
