<?php
use Zend\Form\Element\Submit;
?>
<div id="tituloPagina">Cadastro de tipos de competências</div>
<div id="tabs">
<ul>
<li><a href="#dados">Tipos de competências</a></li>
</ul>
<div id="dados">
<?php
echo $this->form ()->openTag ( $form );
echo $this->formInput ( $form->get ( 'id' ) );

echo $this->formLabel($form->get('titulo'))."<br />";
echo $this->formInput($form->get('titulo'))."<br />";
echo $this->formElementErrors($form->get('titulo'))."<br />";

echo $this->formInput ($form->get ("submit"));
echo $this->form()->closeTag();
?>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
	$("#submit").hide();
	$("#cancelar").button({
		icons: {
			primary: "ui-icon-close",
		},
	text: true,
	});
	$("#salvar").button({
		icons: {
			primary: "ui-icon-disk",
		},
	text: true,
	});

	$("#cancelar").click(function(e) {
		e.preventDefault();
		window.location ="/application/competencia-tipo";
	});

	$("#salvar").click(function(e) {
		e.preventDefault();
		$("#submit").click();
	});

	$("#tabs").tabs();
	
</script>
