<div id="tituloPagina">Cadastro de Turmas<br/><br/>Turmas cadastradas</div>

<table class="hover" id="consulta">
	<thead>
		<tr>
			<th style="text-align: left;">Capacitação</th>
			<th style="text-align: left;">Data inicial</th>
			<th style="text-align: left;">Data Final</th>
			<th style="text-align: left;">Instrutor(es)</th>
			<th style="text-align: left;">Nº Participantes</th>
			<th width="90" class="center">Opções</th>
		</tr>
	</thead>
	<tbody>
	
	<?php 
	foreach($turmas as $turma):?>
		<tr>
			<td><?php echo $this->escapeHtml($turma->getCapacitacao()->getDescricao());?></td>
			<td><?php echo $this->escapeHtml($turma->getInicial());?></td>
			<td><?php echo $this->escapeHtml($turma->getFinal());?></td>
			<td><?php echo $this->escapeHtml($turma->getInstrutor()->getNome());?></td>
			<td><?php echo $this->escapeHtml($turma->getPartiticipantes());?></td>
			<td style="text-align:center">
				<a href="/application/turma/save/id/<?php echo $turma->getId();?>"><span title="Editar" class="ui-icon ui-icon-pencil"/></a>
				<a href="/application/turma/delete/id/<?php echo $turma->getId();?>" id="excluir"><span title="Excluir" class="ui-icon ui-icon-trash"/></a>
			</td> 
		</tr>
	<?php endforeach;?>
	
	</table>
<div id="barraBotoes">
	<button id="novo">Novo...</button>
</div>
<div id="dialog-form" title="Confirmar exclusão">
	<p id="texto"/>
</div>
	<script>
	$("#novo").button({
		icons: {
			primary: "ui-icon-plus",
		},
	text: true,
	});
	$("#novo").click(function(e) {
		e.preventDefault();
		window.location ="/application/turma/save";
	});

    $("input[type=submit], a" ).button();

    $("a#excluir").on("click", function(e) {
        e.preventDefault();
        var link = $(this).attr('href');
        var descricao = $(this).closest('tr').find('#descricao').text();
        $("#texto").html("Deseja realmente excluir '"+descricao+"'?");
        $("#dialog-form").data("link", link);
        $("#dialog-form").dialog("open");
    });

     $( "#dialog-form" ).dialog({
		dialogClass: 'no-close',
        autoOpen: false,
        resizable: false,
        draggable: false,
        height: 200,
        width: 300,
        modal: true,
        buttons: {
     		"Não": function() {
         		$(this).dialog("close");
         	},
     		"Sim": function() {
        		var link = $(this).data("link");
            	window.location = link;
           }
	}
    });
   
</script>
	