<?php
use Zend\Form\Element\Submit;
?>
<div id="tituloPagina">Cadastro de Turma</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Turma</a></li>
	</ul>
	<div id="dados">
<?php
echo $this->form ()->openTag ( $form );
echo $this->formInput ( $form->get ( 'id' ) );

echo $this->formLabel ( $form->get ( 'capacitacao' ) ) . "<br />";
echo $this->formSelect ( $form->get ( 'capacitacao' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'capacitacao' ) ) . "<br />";

echo $this->formLabel ( $form->get ( 'nome' ) ) . "<br />";
echo $this->formInput ( $form->get ( 'nome' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'nome' ) ) . "<br />";

?>

<div id="selecoes">
			<ul>
				<li><a href='#dadosTab'><span>Dados</span></a></li>
				<li><a href='#participantesTab'><span>Participantes</span></a></li>
				<li><a href='#questionarioTab'><span>Questionário</span></a></li>
			</ul>

			<br>
			<div id="dadosTab">
<?php

echo $this->formLabel ( $form->get ( 'forma' ) ) . "<br />";
echo $this->formSelect ( $form->get ( 'forma' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'forma' ) ) . "<br />";

echo $this->formLabel ( $form->get ( 'local' ) ) . "<br />";
echo $this->formInput ( $form->get ( 'local' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'local' ) ) . "<br />";

echo $this->formLabel ( $form->get ( 'valor' ) ) . "<br />";
echo $this->formInput ( $form->get ( 'valor' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'valor' ) ) . "<br />";

echo $this->formLabel ( $form->get ( 'inicial' ) ) . "<br />";
echo $this->formInput ( $form->get ( 'inicial' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'inicial' ) ) . "<br />";

echo $this->formLabel ( $form->get ( 'final' ) ) . "<br />";
echo $this->formInput ( $form->get ( 'final' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'final' ) ) . "<br />";

echo $this->formLabel ( $form->get ( 'instituicao' ) ) . "<br />";
echo $this->formSelect ( $form->get ( 'instituicao' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'instituicao' ) ) . "<br />";

echo $this->formLabel ( $form->get ( 'instrutor' ) ) . "<br />";
echo $this->formSelect ( $form->get ( 'instrutor' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'instrutor' ) ) . "<br />";

echo $this->formLabel ( $form->get ( 'coordenacao' ) ) . "<br />";
echo $this->formSelect ( $form->get ( 'coordenacao' ) ) . "<br />";
echo $this->formElementErrors ( $form->get ( 'coordenacao' ) ) . "<br />";

?>

</div>
			<div id="questionarioTab">
				<fieldset class="coluna100">
					<legend>Questionário</legend>
					<table class="hover" id="tabelaQuestionario">
						<thead>
							<tr>
								<th>Perguntas</th>
								<th>Competências</th>
								<th>Opções</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
					<br>
					<button id="novaPergunta">Adicionar</button>
				</fieldset>
			</div>

			<div id="participantesTab">
				<fieldset class="coluna100">
					<legend> Participantes</legend>
					<table class="hover" id="tabelaParticipantes">
						<thead>
							<tr>
								<th>Mátricula</th>
								<th>Nome</th>
								<!-- <th>Ramal</th>
								<th>Sublotação</th>
								<th>Cargo</th> -->
								<th>Opções</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->empregados as $empregado):?>
						<tr>
								<td><input id="empregado" name="matricula[]"
									value="<?php echo $empregado->getMatricula();?>" type="hidden"><?php echo $this->escapeHtml($empregado->getMatricula());?></td>
								<td><?php echo $this->escapeHtml($empregado->getNome());?></td>
								<td><button
										id="excluirEmpregado_<?php echo $empregado->getMatricula();?>">Remover
										participante</button></td>
							</tr>
						<?php endforeach;?>		
						</tbody>
					</table>
					<br>
					<button id="novoParticipante">Adicionar</button>
					<div id="modal-participantes" title="Adicionar Participantes"
						class="ui-widget">
						<div id="empregados"></div>
					</div> <!-- Botão novaLista não se refere a criar uma "nova lista de espera" -->
					<button id="novalistaEspera">Lista de Espera</button>
					<div id="modal-listaEspera" title="Lista de Espera"
					class="ui-widget">
						<div id="esperas"></div>
					</div>
				</fieldset>
			</div>
		</div>
		<?php
		echo $this->formInput ( $form->get ( "submit" ) );
		echo $this->form ()->closeTag ();
		?>
</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>