<div id="tituloPagina">
	Validação de compêtencias<br />
	<br>
</div>

<table class="hover" id="tabelaValidacao">
	<thead>
		<tr>
			<th style="text-align: left;">Participantes</th>
			<th style="text-align: left;">Competência</th>
			<th width="150" class="center">Opções</th>
		</tr>
	</thead>
	<tbody>
	
	<?php foreach ($turmas as $turma):?>
		<tr>
			<td><?php echo $this->escapeHtml($turma->getParticipantes());?></td>
			<td><?php echo $this->escapeHtml($turma->getCompetencias());?></td>
			<td>oi</td>
		</tr>
	<?php endforeach;?>
	</tbody>
</table>
<script>
$(document).ready(function() {
	var tabelaValid = $("#tabelaValidacao").DataTable({
		  "bInfo": false,
	      "bFilter": false,
	      "bLengthChange": false,
	      "paging": false,
	      "rowId": 'staffId',
	      "oLanguage": {
	      	"sZeroRecords": "",
	      	"sEmptyTable": "",
	      	
	      },
	      "columnDefs": [
	                 { width: "40%", targets: [1] },
	                 { width: "30%", targets: [0] },
	                // { width: "10%", targets: [5] },
	                 { className: "dt-body-center", targets: [0, 1, 2] }
	             ]
	});	
}
</script>