<div id="tituloPagina">Validação de compêtencias<br/><br/> </div>

<table class="hover" id="consulta">
	<thead>
		<tr>
			<th style="text-align: left;">Participantes</th>
			<th style="text-align: left;">Competência</th>
			<th width="150" class="center">Opções</th>
		</tr>
	</thead>
	<tbody>
	
	<?php foreach ($turmas as $turma):?>
		<tr>
			<td><?php echo $this->escapeHtml($turma->getNome());?></td>
			<td><?php echo $this->escapeHtml($turma->getCapacitacao()->getDescricao()); ?></td>
			<td style="text-align:center">
		</tr>
	<?php endforeach;?>
	</tbody>
</table>
<script>

	
</script>