<div id="tituloPagina">Cadastro de Listas de Espera<br/><br/>Listas de espera cadastradas</div>


<table class="hover" id="consulta">
<thead>
<tr>
<th style="text-align: left;">Capacitação</th>
<th width="90" class="center">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($esperas as $espera):?>
		<tr>
		<td id="descricao"><?php echo $this->escapeHtml($espera->getCapacitacao()->getDescricao());?></td>
			<td style="text-align:center">
				<a href="/application/lista-espera/save/id/<?php echo $espera->getId();?>"><span title="Editar" class="ui-icon ui-icon-pencil"/></a>
				<a href="/application/lista-espera/delete/id/<?php echo $espera->getId();?>" id="excluir"><span title="Excluir" class="ui-icon ui-icon-trash"/></a>
			</td> 
		</tr>
	<?php endforeach;?>

</table>
<div id="barraBotoes">
	<button id="novo">Novo...</button>
</div>
<div id="dialog-form" title="Confirmar exclusão">
	<p id="texto"/>
</div>

<script>
$("#novo").button({
	icons: {
		primary: "ui-icon-plus",
	},
text: true,
});
$("#novo").click(function(e) {
	e.preventDefault();
	window.location ="/application/lista-espera/save";
});

$("input[type=submit], a" ).button();

$("a#excluir").on("click", function(e) {
    e.preventDefault();
    var link = $(this).attr('href');
    var nome = $(this).closest('tr').find('#capacitacao').text();
    $("#texto").html("Deseja realmente excluir '"+nome+"'?");
    $("#dialog-form").data("link", link);
    $("#dialog-form").dialog("open");
});

 $( "#dialog-form" ).dialog({
	dialogClass: 'no-close',
    autoOpen: false,
    resizable: false,
    draggable: false,
    height: 200,
    width: 300,
    modal: true,
    buttons: {
    		"Sim": function() {
    		var link = $(this).data("link");
        	window.location = link;
     	  },
 			"Não": function() {
     		$(this).dialog("close");
     	}
}
});
</script>