<?php
use Zend\Form\Element\Submit;
?>
<div id="tituloPagina">Cadastro de cursos</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Curso</a></li>
	</ul>
	<div id="dados">
		<?php
		echo $this->form ()->openTag ( $form );
		// echo $this->formCollection($form);
		echo $this->formInput ( $form->get ( 'id' ) );
		echo $this->formLabel ( $form->get ( 'descricao' ) ) . "<br />";
		echo $this->formInput ( $form->get ( 'descricao' ) ) . "<br />";
		echo $this->formElementErrors ( $form->get ( 'descricao' ) ) . "<br />";
		echo $this->formLabel ( $form->get ( 'cargaHoraria' ) ) . "<br />";
		echo $this->formInput ( $form->get ( 'cargaHoraria' ) ) . "<br />";
		echo $this->formElementErrors ( $form->get ( 'cargaHoraria' ) ) . "<br />";
		echo $this->formInput ($form->get ("submit"));
		?>
		<table id="competenciasCurso">
			<thead>
				<tr>
					<th>Competência</th>
					<th>Tipo Competência</th>
					<th>Opções</th>
				</tr>
			
			</thead>
			<tbody>
			</tbody>
		</table>
		<?php
		
echo $this->form ()->closeTag ();
		?>
		<button id="novaCompetencia">Adicionar competência</button>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<div id="modal-competencia" title="Adicionar competência"
	class="ui-widget">
	<div id="competencias"></div>
</div>
<script>
	$("#submit").hide();
	$("#cancelar").button({
		icons: {
			primary: "ui-icon-close",
		},
	text: true,
	});
	$("#salvar").button({
		icons: {
			primary: "ui-icon-disk",
		},
	text: true,
	});

	$("#cancelar").click(function(e) {
		e.preventDefault();
		window.location ="/application/curso";
	});

	$("#salvar").click(function(e) {
		e.preventDefault();
		$("#submit").click();
	});

	$("#tabs").tabs();
	
</script>
