<div id="tituloPagina">Cadastro de Sublotação</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Sublotação</a></li>
	</ul>
	<div id="dados">
		<?php
 				echo $this->form()->openTag($form);
		
		echo $this->formRow($form->get("id"));
		echo $this->formRow($form->get("descricao"))."<br /><br />";
		echo $this->formRow($form->get("sigla"))."<br /><br />";
		echo $this->formRow($form->get("ano"));
		echo $this->formRow($form->get("submit"));
		?>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
	$("#submit").hide();
	$("#cancelar").button({
		icons: {
			primary: "ui-icon-close",
		},
	text: true,
	});
	$("#salvar").button({
		icons: {
			primary: "ui-icon-disk",
		},
	text: true,
	});

	$("#cancelar").click(function(e) {
		e.preventDefault();
		window.location ="/application/sublotacao";
	});

	$("#salvar").click(function(e) {
		e.preventDefault();
		$("#submit").click();
	});

	$("#tabs").tabs();
	
</script>
