<div id="tituloPagina">Cadastro de cargo<br/><br/>Cargos cadastrados</div>


<table class="hover" id="consulta">
	<thead>
		<tr>
			<th style="text-align: left;">Descrição</th>
			<th>PCS/PCE</th>
			<th width="90" class="center">Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($cargos as $cargo):?>
		<tr>
			<td id="descricao"><?php echo $this->escapeHtml($cargo->getDescricao());?></td>
			<td><?php echo $this->escapeHtml($cargo->getPce());?></td>
			<td style="text-align:center">
				<a href="/application/cargo/save/id/<?php echo $cargo->getId();?>"><span title="Editar" class="ui-icon ui-icon-pencil"/></a>
				<!-- Remoção do botão delete
				<a href="/application/cargo/delete/id/<?php echo $cargo->getId();?>" id="excluir"><span title="Excluir" class="ui-icon ui-icon-trash"/></a>
			</td> -->
		</tr>
	<?php endforeach;?>
</table>
<div id="barraBotoes">
	<button id="novo">Novo...</button>
</div>
<div id="dialog-form" title="Confirmar exclusão">
	<p id="texto"/>
</div>

<script>
	$("#novo").button({
		icons: {
			primary: "ui-icon-plus",
		},
	text: true,
	});
	$("#novo").click(function(e) {
		e.preventDefault();
		window.location ="/application/cargo/save";
	});

    $("input[type=submit], a" ).button();

    $("a#excluir").on("click", function(e) {
        e.preventDefault();
        var link = $(this).attr('href');
        var descricao = $(this).closest('tr').find('#descricao').text();
        $("#texto").html("Deseja realmente excluir '"+descricao+"'?");
        $("#dialog-form").data("link", link);
        $("#dialog-form").dialog("open");
    });

     $( "#dialog-form" ).dialog({
		dialogClass: 'no-close',
        autoOpen: false,
        resizable: false,
        draggable: false,
        height: 200,
        width: 300,
        modal: true,
        buttons: {
     		"Não": function() {
         		$(this).dialog("close");
         	},
     		"Sim": function() {
        		var link = $(this).data("link");
            	window.location = link;
           }
	}
    });
   
</script>
