<div id="tituloPagina">Cadastro de capacitações<br/><br/>Capacitações cadastradas</div>


<table class="hover" id="consulta">
<thead>
<tr>
<th style="text-align: left;">Descrição</th>
<th style="text-align: left;">Tipo de cpacitação</th>
<th style="text-align: left;">Competências</th>
<!-- <th style="text-align: left;">Carga horaria</th> -->
<th width="90" class="center">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($capacitacoes as $capacitacao):?>
		<tr>
			<td><?php echo $this->escapeHtml($capacitacao->getDescricao());?></td>
			<td><?php echo $this->escapeHtml($capacitacao->getCapacitacaoTipo()->getDescricao());?></td>
			<td><?php foreach ($capacitacao->getCompetencias() as $competencia): 
			//Sem $this->escapeHtml (remove os codigo html do echo
			//quebra de linhas do elemento foreach e mostrar na página
			 echo $competencia->getTitulo()."<br>";
			endforeach;?></td>
			<!-- <td><?php // echo $this->escapeHtml($capacitacao->getCargaHoraria());?></td> -->
			<td style="text-align:center">
				<a href="/application/capacitacao/save/id/<?php echo $capacitacao->getId();?>"><span title="Editar" class="ui-icon ui-icon-pencil"/></a>
				<a href="/application/capacitacao/delete/id/<?php echo $capacitacao->getId();?>" id="excluir"><span title="Excluir" class="ui-icon ui-icon-trash"/></a>
			</td> 
		</tr>
	<?php endforeach;?>
</table>
<div id="barraBotoes">
	<button id="novo">Novo...</button>
</div>
<div id="dialog-form" title="Confirmar exclusão">
	<p id="texto"/>
</div>

<script>
	$("#novo").button({
		icons: {
			primary: "ui-icon-plus",
		},
	text: true,
	});
	$("#novo").click(function(e) {
		e.preventDefault();
		window.location ="/application/capacitacao/save";
	});

    $("input[type=submit], a" ).button();

    $("a#excluir").on("click", function(e) {
        e.preventDefault();
        var link = $(this).attr('href');
        var descricao = $(this).closest('tr').find('#descricao').text();
        $("#texto").html("Deseja realmente excluir '"+descricao+"'?");
        $("#dialog-form").data("link", link);
        $("#dialog-form").dialog("open");
    });

     $( "#dialog-form" ).dialog({
		dialogClass: 'no-close',
        autoOpen: false,
        resizable: false,
        draggable: false,
        height: 200,
        width: 300,
        modal: true,
        buttons: {
     	   		"Sim": function() {
        		var link = $(this).data("link");
            	window.location = link;
           },
       		"Não": function() {
     		$(this).dialog("close");
     	}
	}
    });
   
</script>
