<?php
use Zend\Form\Element\Submit;
?>
<div id="tituloPagina">Cadastro de capacitações</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Capacitacao</a></li>
	</ul>
	<div id="dados">
		<?php
		echo $this->form ()->openTag ( $form );
		echo $this->formInput ( $form->get ( 'id' ) );
		
		echo $this->formLabel ( $form->get ( 'capacitacaoTipo' ) ) . "<br />";
		echo $this->formSelect ( $form->get ( 'capacitacaoTipo' ) ) . "<br />";
		echo $this->formElementErrors ( $form->get ( 'capacitacaoTipo' ) ) . "<br />";
		
		echo $this->formLabel ( $form->get ( 'descricao' ) ) . "<br />";
		echo $this->formInput ( $form->get ( 'descricao' ) ) . "<br />";
		echo $this->formElementErrors ( $form->get ( 'descricao' ) ) . "<br />";
		
		// echo $this->formLabel ( $form->get ( 'cargaHoraria' ) ) . "<br />";
		// echo $this->formInput ( $form->get ( 'cargaHoraria' ) ) . "<br />";
		// echo $this->formElementErrors ( $form->get ( 'cargaHoraria' ) ) . "<br />";
		
		echo $this->formInput ( $form->get ( "submit" ) );
		?>
		<table id="competenciasCapacitacao">
			<thead>
				<tr>
					<th>Competência</th>
					<th>Modalidade</th>
					<th>Opções</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->competencias as $competencia):?>
			<tr>
					<td><input id="competencia" name="competencia[]"
						value="<?php echo $competencia->getId();?>" type="hidden"><?php echo $this->escapeHtml($competencia->getTitulo());?></td>
					<td><?php echo $this->escapeHtml($competencia->getModalidade()->getTitulo());?></td>
					<td><button
							id="excluirCompetencia_<?php echo $competencia->getId();?>">Remover
							competência</button></td>
				</tr>
			<?php endforeach;?>			
			</tbody>
		</table>
		<?php
		
		echo $this->form ()->closeTag ();
		?>
		<button id="novaCompetencia">Adicionar competência</button>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<div id="modal-competencia" title="Adicionar competência"
	class="ui-widget">
	<div id="competencias"></div>
</div>
