<?php
use Zend\Form\Element\Submit;
?>
<div id="tituloPagina">Cadastro de Instituições</div>
<div id="tabs">
<ul>
<li><a href="#dados">Instituição</a></li>
</ul>
<div id="dados">

<?php
echo $this->form()->openTag($form);
echo $this->formInput($form->get('codigo'));

echo $this->formLabel($form->get('cnpj'))."<br />";
echo $this->formInput($form->get('cnpj'))."<br />";
echo $this->formElementErrors($form->get('cnpj'))."<br />";

echo $this->formLabel($form->get('inscricaoEstadual'))."<br />";
echo $this->formInput($form->get('inscricaoEstadual'))."<br />";
echo $this->formElementErrors($form->get('inscricaoEstadual'))."<br />";

echo $this->formLabel($form->get('razao'))."<br />";
echo $this->formInput($form->get('razao'))."<br />";
echo $this->formElementErrors($form->get('razao'))."<br />";

echo $this->formLabel($form->get('fantasia'))."<br />";
echo $this->formInput($form->get('fantasia'))."<br />";
echo $this->formElementErrors($form->get('fantasia'))."<br />";

echo $this->formLabel($form->get('cep'))."<br />";
echo $this->formInput($form->get('cep'))."<br />";
echo $this->formElementErrors($form->get('cep'))."<br />";

echo $this->formLabel($form->get('endereco'))."<br />";
echo $this->formInput($form->get('endereco'))."<br />";
echo $this->formElementErrors($form->get('endereco'))."<br />";

echo $this->formLabel($form->get('bairro'))."<br />";
echo $this->formInput($form->get('bairro'))."<br />";
echo $this->formElementErrors($form->get('bairro'))."<br />";

echo $this->formLabel($form->get('cidade'))."<br />";
echo $this->formInput($form->get('cidade'))."<br />";
echo $this->formElementErrors($form->get('cidade'))."<br />";

echo $this->formLabel($form->get('uf'))."<br />";
echo $this->formSelect($form->get('uf'))."<br />";
echo $this->formElementErrors($form->get('uf'))."<br />";

echo $this->formLabel($form->get('pais'))."<br />";
echo $this->formInput($form->get('pais'))."<br />";
echo $this->formElementErrors($form->get('pais'))."<br />";

echo $this->formLabel($form->get('caixaPostal'))."<br />";
echo $this->formInput($form->get('caixaPostal'))."<br />";
echo $this->formElementErrors($form->get('caixaPostal'))."<br />";

echo $this->formLabel($form->get('email'))."<br />";
echo $this->formInput($form->get('email'))."<br />";
echo $this->formElementErrors($form->get('email'))."<br />";

echo $this->formLabel($form->get('telefone'))."<br />";
echo $this->formInput($form->get('telefone'))."<br />";
echo $this->formElementErrors($form->get('telefone'))."<br />";

echo $this->formLabel($form->get('homepage'))."<br />";
echo $this->formInput($form->get('homepage'))."<br />";
echo $this->formElementErrors($form->get('homepage'))."<br />";

echo $this->formLabel($form->get('observacao'))."<br />";
echo $this->formInput($form->get('observacao'))."<br />";
echo $this->formElementErrors($form->get('observacao'))."<br />";


echo $this->formInput ($form->get ("submit"));
echo $this->form()->closeTag();
?>
</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
 	$("#submit").hide();
	$("#cancelar").button({
		icons: {
			primary: "ui-icon-close",
		},
	text: true,
	});
	$(document).ready(function(){
		  $('#cnpj').mask('00.000.000/0000-00');
		  $('#cep').mask('00000-000');
		  $('#inscricaoEstadual').mask('000.000.00-0'); 
		  });
	$('#telefone').focusout(function(){
	    var phone, element;
	    element = $(this);
	    element.unmask();
	    phone = element.val().replace(/\D/g, '');
	    if(phone.length > 10) {
	        element.mask("(99)99999-9999");
	    } else {
	        element.mask("(99)9999-99999");
	    }
	}).trigger('focusout');

$("#uf").selectmenu();
$("#salvar").button({
	icons: {
		primary: "ui-icon-disk",
	},
text: true,
});

$("#cancelar").click(function(e) {
	e.preventDefault();
	window.location ="/application/instituicao";
});

$("#salvar").click(function(e) {
	e.preventDefault();
	$("#submit").click();
});

$("#tabs").tabs();
</script>
