<div id="tituloPagina">Cadastro de competências</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Competência</a></li>
	</ul>
	<div id="dados">
		<?php
			echo $this->form()->openTag($form);
		// 			echo $this->formCollection($form);
		echo $this->formInput($form->get('id'));
		echo $this->formLabel($form->get('titulo'))."<br />";
		echo $this->formInput($form->get('titulo'))."<br />";
		echo $this->formElementErrors($form->get('titulo'))."<br />";
		echo $this->formLabel($form->get('modalidade'))."<br />";
		echo $this->formSelect($form->get('modalidade'))."<br />";
		echo $this->formElementErrors($form->get('modalidade'))."<br />";
		echo $this->formSubmit($form->get('submit'))."<br />";
			echo $this->form()->closeTag();
		?>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
	$("#submit").hide();
	$("#cancelar").button({
		icons: {
			primary: "ui-icon-close",
		},
	text: true,
	});
	$("#modalidade").selectmenu();
	$("#salvar").button({
		icons: {
			primary: "ui-icon-disk",
		},
	text: true,
	});

	$("#cancelar").click(function(e) {
		e.preventDefault();
		window.location ="/application/competencia";
	});

	$("#salvar").click(function(e) {
		e.preventDefault();
		$("#submit").click();
	});

	$("#titulo").selectmenu();
	$("#tabs").tabs();
	
</script>
