<div id="tituloPagina">Cadastro de Equipe Técnica</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Equipe Técnica</a></li>
	</ul>
	<div id="dados">
		<?php
		
		
		echo $this->form()->openTag($form);
		// 			echo $this->formCollection($form);
		echo $this->formInput($form->get('id'));
		echo $this->formLabel($form->get('descricao'))."<br />";
		echo $this->formInput($form->get('descricao'))."<br />";
		echo $this->formElementErrors($form->get('descricao'))."<br />";
		
		echo $this->formLabel($form->get('lider'))."<br />";
		echo $this->formSelect($form->get('lider'))."<br />";
		echo $this->formElementErrors($form->get('lider'))."<br />";
		echo $this->form()->closeTag();
		
// 			echo $this->form()->openTag($form);
// 			echo $this->formCollection($form);
// 			echo $this->form()->closeTag();
		?>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
	$("#submit").hide();
	$("#cancelar").button({
		icons: {
			primary: "ui-icon-close",
		},
	text: true,
	});
	$("#salvar").button({
		icons: {
			primary: "ui-icon-disk",
		},
	text: true,
	});

	$("#cancelar").click(function(e) {
		e.preventDefault();
		window.location ="/application/equipe-tecnica";
	});

	$("#salvar").click(function(e) {
		e.preventDefault();
		$("#submit").click();
	});

	$("#tabs").tabs();
	
</script>
