<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Instituicao extends \Application\Model\Instituicao implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'codigo', 'empregados', 'razao', 'fantasia', 'lideranca', 'endereco', 'bairro', 'telefone', 'telefone2', 'telefone3', 'fax', 'caixaPostal', 'cep', 'cidade', 'uf', 'regiao', 'cnpj', 'inscricaoEstadual', 'homepage', 'email', 'tipoInstituicao', 'ramo', 'dataAtualizacao', 'situacao', 'observacao', 'recebeNewsletter', 'tipoPessoa', 'pais', 'logomarca', 'ativo', 'inadimplente', 'senha', 'dataNascimentoFundacao', 'estadoCivil', 'sexo', 'infoEmbrapa', 'passaporte', 'dataInclusao', 'inclusao', 'dataAlteracao', 'alteracao', 'formacao', 'profissao', 'cargo', 'subcategoria', 'categoria', 'facilitadores', 'primaryKeyField', 'tableName', 'inputFilter'];
        }

        return ['__isInitialized__', 'codigo', 'empregados', 'razao', 'fantasia', 'lideranca', 'endereco', 'bairro', 'telefone', 'telefone2', 'telefone3', 'fax', 'caixaPostal', 'cep', 'cidade', 'uf', 'regiao', 'cnpj', 'inscricaoEstadual', 'homepage', 'email', 'tipoInstituicao', 'ramo', 'dataAtualizacao', 'situacao', 'observacao', 'recebeNewsletter', 'tipoPessoa', 'pais', 'logomarca', 'ativo', 'inadimplente', 'senha', 'dataNascimentoFundacao', 'estadoCivil', 'sexo', 'infoEmbrapa', 'passaporte', 'dataInclusao', 'inclusao', 'dataAlteracao', 'alteracao', 'formacao', 'profissao', 'cargo', 'subcategoria', 'categoria', 'facilitadores', 'primaryKeyField', 'tableName', 'inputFilter'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Instituicao $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodigo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazao', []);

        return parent::getRazao();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazao($razao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazao', [$razao]);

        return parent::setRazao($razao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFantasia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFantasia', []);

        return parent::getFantasia();
    }

    /**
     * {@inheritDoc}
     */
    public function setFantasia($fantasia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFantasia', [$fantasia]);

        return parent::setFantasia($fantasia);
    }

    /**
     * {@inheritDoc}
     */
    public function getLideranca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLideranca', []);

        return parent::getLideranca();
    }

    /**
     * {@inheritDoc}
     */
    public function setLideranca($lideranca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLideranca', [$lideranca]);

        return parent::setLideranca($lideranca);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', []);

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco($endereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', [$endereco]);

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', []);

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro($bairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', [$bairro]);

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', []);

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($telefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', [$telefone]);

        return parent::setTelefone($telefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone2', []);

        return parent::getTelefone2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone2($telefone2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone2', [$telefone2]);

        return parent::setTelefone2($telefone2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone3', []);

        return parent::getTelefone3();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone3($telefone3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone3', [$telefone3]);

        return parent::setTelefone3($telefone3);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaixaPostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaixaPostal', []);

        return parent::getCaixaPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaixaPostal($caixaPostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaixaPostal', [$caixaPostal]);

        return parent::setCaixaPostal($caixaPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', []);

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', [$cep]);

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', []);

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', [$cidade]);

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUf', []);

        return parent::getUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setUf($uf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUf', [$uf]);

        return parent::setUf($uf);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegiao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegiao', []);

        return parent::getRegiao();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegiao($regiao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegiao', [$regiao]);

        return parent::setRegiao($regiao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnpj', []);

        return parent::getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnpj($cnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnpj', [$cnpj]);

        return parent::setCnpj($cnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscricaoEstadual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscricaoEstadual', []);

        return parent::getInscricaoEstadual();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscricaoEstadual($inscricaoEstadual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscricaoEstadual', [$inscricaoEstadual]);

        return parent::setInscricaoEstadual($inscricaoEstadual);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomepage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomepage', []);

        return parent::getHomepage();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomepage($homepage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomepage', [$homepage]);

        return parent::setHomepage($homepage);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoInstituicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoInstituicao', []);

        return parent::getTipoInstituicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoInstituicao($tipoInstituicao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoInstituicao', [$tipoInstituicao]);

        return parent::setTipoInstituicao($tipoInstituicao);
    }

    /**
     * {@inheritDoc}
     */
    public function getRamo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRamo', []);

        return parent::getRamo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRamo($ramo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRamo', [$ramo]);

        return parent::setRamo($ramo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAtualizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAtualizacao', []);

        return parent::getDataAtualizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAtualizacao($dataAtualizacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAtualizacao', [$dataAtualizacao]);

        return parent::setDataAtualizacao($dataAtualizacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituacao', []);

        return parent::getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituacao($situacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituacao', [$situacao]);

        return parent::setSituacao($situacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', []);

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', [$observacao]);

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecebeNewsletter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecebeNewsletter', []);

        return parent::getRecebeNewsletter();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecebeNewsletter($recebeNewsletter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecebeNewsletter', [$recebeNewsletter]);

        return parent::setRecebeNewsletter($recebeNewsletter);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoPessoa', []);

        return parent::getTipoPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoPessoa($tipoPessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoPessoa', [$tipoPessoa]);

        return parent::setTipoPessoa($tipoPessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogomarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogomarca', []);

        return parent::getLogomarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogomarca($logomarca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogomarca', [$logomarca]);

        return parent::setLogomarca($logomarca);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', []);

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', [$ativo]);

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getInadimplente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInadimplente', []);

        return parent::getInadimplente();
    }

    /**
     * {@inheritDoc}
     */
    public function setInadimplente($inadimplente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInadimplente', [$inadimplente]);

        return parent::setInadimplente($inadimplente);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', []);

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', [$senha]);

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimentoFundacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimentoFundacao', []);

        return parent::getDataNascimentoFundacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimentoFundacao($dataNascimentoFundacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimentoFundacao', [$dataNascimentoFundacao]);

        return parent::setDataNascimentoFundacao($dataNascimentoFundacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoCivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoCivil', []);

        return parent::getEstadoCivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoCivil($estadoCivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoCivil', [$estadoCivil]);

        return parent::setEstadoCivil($estadoCivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfoEmbrapa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfoEmbrapa', []);

        return parent::getInfoEmbrapa();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfoEmbrapa($infoEmbrapa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfoEmbrapa', [$infoEmbrapa]);

        return parent::setInfoEmbrapa($infoEmbrapa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassaporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassaporte', []);

        return parent::getPassaporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassaporte($passaporte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassaporte', [$passaporte]);

        return parent::setPassaporte($passaporte);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInclusao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInclusao', []);

        return parent::getDataInclusao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInclusao($dataInclusao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInclusao', [$dataInclusao]);

        return parent::setDataInclusao($dataInclusao);
    }

    /**
     * {@inheritDoc}
     */
    public function getInclusao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInclusao', []);

        return parent::getInclusao();
    }

    /**
     * {@inheritDoc}
     */
    public function setInclusao($inclusao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInclusao', [$inclusao]);

        return parent::setInclusao($inclusao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAlteracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAlteracao', []);

        return parent::getDataAlteracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAlteracao($dataAlteracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAlteracao', [$dataAlteracao]);

        return parent::setDataAlteracao($dataAlteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlteracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlteracao', []);

        return parent::getAlteracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlteracao($alteracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlteracao', [$alteracao]);

        return parent::setAlteracao($alteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormacao', []);

        return parent::getFormacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormacao($formacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormacao', [$formacao]);

        return parent::setFormacao($formacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfissao', []);

        return parent::getProfissao();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfissao($profissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfissao', [$profissao]);

        return parent::setProfissao($profissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', []);

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo($cargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', [$cargo]);

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubcategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubcategoria', []);

        return parent::getSubcategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubcategoria($subcategoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubcategoria', [$subcategoria]);

        return parent::setSubcategoria($subcategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria($categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpregados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpregados', []);

        return parent::getEmpregados();
    }

    /**
     * {@inheritDoc}
     */
    public function getInstituicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstituicao', []);

        return parent::getInstituicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstituicao($instituicao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstituicao', [$instituicao]);

        return parent::setInstituicao($instituicao);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', []);

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getTableName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTableName', []);

        return parent::getTableName();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', [$data]);

        return parent::exchangeArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', []);

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', [$inputFilter]);

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
