<div id="tituloPagina">Cadastro de Outras Funções</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Outra Função</a></li>
	</ul>
	<div id="dados">
		<?php
			echo $this->form()->openTag($form);
			echo $this->formCollection($form);
			echo $this->form()->closeTag();
		?>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
	$("#submit").hide();
	$("#cancelar").button({
		icons: {
			primary: "ui-icon-close",
		},
	text: true,
	});
	$("#salvar").button({
		icons: {
			primary: "ui-icon-disk",
		},
	text: true,
	});

	$("#cancelar").click(function(e) {
		e.preventDefault();
		window.location ="/application/outra-funcao";
	});

	$("#salvar").click(function(e) {
		e.preventDefault();
		$("#submit").click();
	});

	$("#tabs").tabs();
	
</script>
