<div id="tituloPagina">Cadastro de subárea de atuação<br/><br/>Subáreas de atuação cadastradas</div>

<table class="hover" id="consulta">
	<thead>
		<tr>
			<th style="text-align: left;">Área</th>
			<th style="text-align: left;">Subárea</th>
			<th width="90" class="center">Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($areas as $area):?>
		<tr>
			<td id="descricao"><?php echo $this->escapeHtml($area->getDescricao());?></td>
			<td></td>
			<td></td>
		</tr>
		<?php foreach($area->getSubareas() as $subarea):?>
			<tr>
				<td></td>
				<td><?php echo $this->escapeHtml($subarea->getDescricao());?></td>
				<td style="text-align:center">
					<a href="/application/subarea/save/id/<?php echo $subarea->getId();?>"><span title="Editar" class="ui-icon ui-icon-pencil"/></a>
					<!-- Remoção do botão "delete"
					<a href="/application/subarea/delete/id/<?php echo $subarea->getId();?>" id="excluir"><span title="Excluir" class="ui-icon ui-icon-trash"/></a>
				</td> -->
			</tr>
		<?php endforeach;?>
	<?php endforeach;?>
</table>
<div id="barraBotoes">
	<button id="novo">Novo...</button>
</div>
<div id="dialog-form" title="Confirmar exclusão">
	<p id="texto"/>
</div>

<script>
	$("#novo").button({
		icons: {
			primary: "ui-icon-plus",
		},
	text: true,
	});
	$("#novo").click(function(e) {
		e.preventDefault();
		window.location ="/application/subarea/save";
	});

    $("input[type=submit], a" ).button();

    $("a#excluir").on("click", function(e) {
        e.preventDefault();
        var link = $(this).attr('href');
        var descricao = $(this).closest('tr').find('#descricao').text();
        $("#texto").html("Deseja realmente excluir '"+descricao+"'?");
        $("#dialog-form").data("link", link);
        $("#dialog-form").dialog("open");
    });

     $( "#dialog-form" ).dialog({
		dialogClass: 'no-close',
        autoOpen: false,
        resizable: false,
        draggable: false,
        height: 200,
        width: 300,
        modal: true,
        buttons: {
     		"Não": function() {
         		$(this).dialog("close");
         	},
     		"Sim": function() {
        		var link = $(this).data("link");
            	window.location = link;
           }
	}
    });

	$('#consulta').dataTable({
    	"bLengthChange": false,
    	"bSort": false
     });
   
</script>
